# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 19:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20160820_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
