# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_options_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='starting_bet',
            field=models.FloatField(default=1),
        ),
    ]
