# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 11:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20160902_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='pair_number',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='options',
            name='starting_bet',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='options',
            name='step',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
