# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20160903_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='pair_number',
            new_name='pairs',
        ),
    ]
