# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20160903_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='rows',
        ),
        migrations.AddField(
            model_name='options',
            name='real_player_rows',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='options',
            name='virtual_play_rows',
            field=models.BooleanField(default=True),
        ),
    ]
