# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20160917_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='play_column',
            new_name='choice_column',
        ),
    ]
