# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20160917_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='player_column',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
