# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_round_player_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='bet_column',
            new_name='bet',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='choice_column',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='debt_column',
            new_name='debt',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='index_column',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='level_column',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='net_column',
            new_name='net',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='partner_column',
            new_name='partner',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='player_column',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='result_column',
            new_name='result',
        ),
    ]
