# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20160918_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='number',
            new_name='iteration',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='user',
            new_name='user_id',
        ),
    ]
