# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20161015_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
