# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20161015_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
