# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20161016_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='play_column',
            new_name='choice_column',
        ),
    ]
